// Exemplo 7: - “Exemplo de criação parcial de duas trigges”

//TRIGGER 1
CREATE TRIGGER TRIGGER_TESTE1
BEFORE UPDATE OF
IDADEALU,NOMEALU ON TBALUNO
BEGIN
NULL;
END;

TRIGGER 2
CREATE TRIGGER TRIGGER_TESTE2
AFTER INSERT OR DELETE OR
UPDATE ON TBALUNO
BEGIN
NULL;
END;
