// Exemplo 8: - “Exemplo definição de tipo de trigger”

// TRIGGER 3
CREATE TRIGGER TRIGGER_TESTE3
ALTER UPDATE OR DELETE ON TBALUNO
BEGIN
NULL;
END;

// TRIGGER 4
CREATE TRIGGER TRIGGER_TESTE4
BEFORE INSERT OR DELETE ON TBALUNO
FOR EACH ROW
BEGIN
NULL;
END;
